# Generated by Django 6.0.1 on 2026-01-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='booking_url',
            field=models.URLField(blank=True, help_text='External booking link', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this destination active/available?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Full location description', max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='objectives_supported',
            field=models.JSONField(blank=True, default=list, help_text='List of supported travel objectives'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='accommodation_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('hostel', 'Hostel'), ('guesthouse', 'Guest House')], default='hotel', help_text='Preferred accommodation type', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='location',
            field=models.CharField(blank=True, help_text='Preferred location', max_length=200),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='objective',
            field=models.CharField(choices=[('leisure', 'Leisure'), ('adventure', 'Adventure'), ('honeymoon', 'Honeymoon'), ('business', 'Business'), ('family', 'Family')], default='leisure', help_text='Travel objective', max_length=20),
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Image URL')),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary/featured image?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.destination')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
